version: "3.8"

services:
  postgres:
    container_name: postgres
    image: postgres
    volumes:
      - pg-data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"
    restart: unless-stopped

  server-lamoda:
    container_name: server-lamoda
    build: .
    env_file:
      - .env
    ports:
      - "${HTTP_PORT}:${HTTP_PORT}"
    depends_on:
      - postgres
    restart: unless-stopped

  # client-lamoda:
  #   container_name: client-lamoda
  #   build: ./client
  #   restart: unless-stopped

volumes:
  pg-data:

    
